[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'


## View
[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_source = '''
let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'junegunn/goyo.vim'


[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_source = '''
let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -l -g ""'
'''


## auto completion
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tpope/vim-surround'

## Git
[[plugins]]
repo = 'tpope/vim-fugitive'


## C++
[[plugins]]
repo = 'Valloric/YouCompleteMe'
merged = 0
hook_source = '''
let g:ycm_global_ycm_extra_conf = '${HOME}/.ycm_extra_conf.py'
let g:ycm_auto_trigger = 0
let g:ycm_autoclose_preview_window_after_insertion = 1
'''
build = './install.py'


## denite
[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/denite.nvim'


